<?php

declare(strict_types=1);

return [
    'app_timezone' => 'America/Bogota',
    'db_host' => 'localhost',
    'db_name' => 'u873298580_agenda',
    'db_user' => 'u873298580_administrador',
    'db_password' => 'Dominio.2026',
    'whatsapp_provider' => 'textmebot',
    'whatsapp_cron_secret' => 'cambia-este-secreto',
    'textmebot_api_key' => '',
    'textmebot_reminder_api_key' => '',
    'textmebot_booking_api_key' => '',
    'twilio_account_sid' => '',
    'twilio_auth_token' => '',
    'twilio_whatsapp_from' => 'whatsapp:+14155238886',
    'twilio_reminder_whatsapp_from' => '',
    'twilio_booking_whatsapp_from' => '',
    'twilio_content_sid' => '',
    'twilio_booking_admin_content_sid' => '',
    'twilio_booking_professional_content_sid' => '',
    'twilio_booking_customer_content_sid' => '',
    'telegram_bot_token' => '8150851616:AAG2-IUqUeYQRI4jDWeYku2Z3Irc_93LVms',
    'telegram_bot_username' => 'SteelSoft_bot',
    'telegram_cron_secret' => 'cambia-este-secreto-telegram',
    'system_admin_name' => 'Julian Esteban Nunez',
    'system_admin_username' => 'admin',
    'system_admin_email' => 'administrador@steelsoft.com.co',
    'system_admin_password' => 'Dominio.2026',
    'mail_from_name' => 'SteelSoft Agenda',
    'mail_from_email' => 'info@steelsoft.com.co',
    'mail_transport' => 'smtp',
    'smtp_host' => 'smtp.hostinger.com',
    'smtp_port' => 465,
    'smtp_encryption' => 'ssl',
    'smtp_username' => 'info@steelsoft.com.co',
    'smtp_password' => 'Dominio.2026',
];
